[package]
name = "env-file-parser"
version = "1.0.1"
edition = "2021"
description = "Reads .env files and returns key-value pairs. No dependencies, no env mutation."
license = "MIT"
readme = "README.md"
repository = "https://github.com/SharmaDevanshu089/env-loader"
homepage = "https://github.com/SharmaDevanshu089/env-loader"
documentation = "https://docs.rs/env-loader"
keywords = ["env", "dotenv", "config", "parser", "environment"]
categories = ["config", "parser-implementations"]

[dependencies]